### ISSUE TITLE
Problems connecting to vRO when it is configured for SSO authentication

### ISSUE THREAD

**Issue by jaristizabalc** [vmw-loginsight/webhook-shims#39]
Hello,

I followed the procedure on https://blogs.vmware.com/management/2017/02/self-healing-data-center-part-4.html but I keep getting a 401 response every time the shim sends the request to vRO:

2017-07-17 20:39:39,623 INFO URL=https://10.65.65.110:8281/vco/api/workflows/891596b4-c5a5-4bf2-ac26-bbb20090ae15/executions
2017-07-17 20:39:39,624 INFO Headers={'Content-type': 'application/json'}
2017-07-17 20:39:39,624 INFO Body={"parameters": [{"name": "alertId", "scope": "local", "type": "string", "value": {"string": {"value": "6f2d0b2a-e566-4d7b-bdc6-602d9b31c37b"}}}]}
2017-07-17 20:39:39,624 INFO Check=False
2017-07-17 20:39:39,628 DEBUG Starting new HTTPS connection (1): 10.65.65.110
/root/webhook-shims/venv-webhookshims/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 InsecureRequestWarning)
2017-07-17 20:39:39,658 DEBUG https://10.65.65.110:8281 "POST /vco/api/workflows/891596b4-c5a5-4bf2-ac26-bbb20090ae15/executions HTTP/1.1" 401 1154
2017-07-17 20:39:39,660 INFO 10.66.65.227 - - [17/Jul/2017 20:39:39] "POST /endpoint/vro/891596b4-c5a5-4bf2-ac26-bbb20090ae15/6f2d0b2a-e566-4d7b-bdc6-602d9b31c37b HTTP/1.1" 401 -

I found this information as well on the vRO Swagger:

"Single Sign-On Authentication
If Orchestrator is configured with the vCenter Single Sign-On (SSO) server, you need a principal holder-of-key (HoK) token to access system objects in Orchestrator through the REST API.
The HoK token is passed as a request Authorization header element. The value must be gzip, base64
encoded string.

To be able to test the service bellow you need to enable basic authentication over sso.
This happens by adding the following property to vmo.properties configuration file:

com.vmware.o11n.sso.basic-authentication.enabled = true "

I added the line to the vRO config and restarted the appliance, now I can send requests using Swagger using the syntax user@domain, but still no luck with the shim.

In the shims examples the syntax is administrator@vsphere.local, same as I have it on the netrc file. Is somebody aware or any other requirements?, do I need a HoK token to make this work?

Thank you,

Juan.

**Comment by johnddias** [comment]
I'll have to bone up on using SSO with vRO and see if I can get this working.

**Comment by johnddias** [comment]
So, I set my vRO instance up for SSO and added the line for vmo.properties you mention above.  I added my domain credentials to .netrc and everything seems to work fine for me (getting 202, and the workflow runs).

Did you set up RBAC in the Orchestrator configurator?

**Comment by jaristizabalc** [comment]
Hi John,

My .netrc  file looks like this:

machine vro_appliance.lab.local
login vroadmin@vsphere.local
password XXXXX

The RBAC on vRO is set to SSO and the vroadmin user has admin privileges.

Thanks,

Juan.

**Comment by johnddias** [comment]
Well, rats.  I cannot recreate this problem since it works for me.  Is your
.netrc in the user home directory for the account that is running the shims?

**Comment by jaristizabalc** [comment]
.netrc is on the home directory of root. 

root@XXXX [ ~ ]# ls -lah ~
total 1.6M
drwxr-x---  5 root root 4.0K Aug  4 14:32 .
drwxr-xr-x 15 root root 4.0K Jan 11  2017 ..
-rw-------  1 root root 2.0K Jul 20 22:28 .bash_history
drwx------  3 root root 4.0K Jul  7 19:40 .cache
-rw-------  1 root root   84 Jul 18 16:51 .netrc
drwxr-x---  7 root root 4.0K Jul  7 21:17 webhook-shims

**Comment by johnddias** [comment]
Is it working without using .netrc?  Like config the VROUSER and VROPASS vars and disable USERNETRC.  I don't think .netrc is the problem here but trying to boil this down the the simplest config possible.

**Comment by jaristizabalc** [comment]
Hi John,

It worked fine disabling the USERNTRC and setting the values directly on the config file. I am getting a 202 response and the workflow is getting executed on vRO.

Thanks for your help.

Juan.
