### ISSUE TITLE
using mutilple endpoints at a time

### ISSUE THREAD

**Issue by sinu** [vmw-loginsight/webhook-shims#59]
Hello is there any option to use multiple endpoints  together exp use pagerduty and slack endpoint together

**Comment by johnddias** [comment]
As is, to do this you would need to create an alert notification in vROps or webhook in LI, for each endpoint and trigger on the same alert conditions.  I thinl that would work.

**Comment by vmw-loginsight** [comment]
As John mentioned, both vROps and LI support multiple webhook destinations so you could specify both PagerDuty and Slack.
