### ISSUE TITLE
Slack integration fails with "METHOD NOT ALLOWED"

### ISSUE THREAD

**Issue by KKelling** [vmw-loginsight/webhook-shims#61]
Hi.  I deployed this but I'm not smart enough to know if its failing because I missed a step or something else.

I edited slack.py by adding the full URL for my Slack webhook.

When I test it, I see the attempted on the shim listener, but the response is "METHOD NOT ALLOWED".

Any thoughts on what might be missing?  Thanks!

![2018-02-25 13_30_21-z - paint](https://user-images.githubusercontent.com/31494687/36644978-15097074-1a30-11e8-9e1f-66b2a8df899b.png)

**Comment by vmw-loginsight** [comment]
What is the webhook destination URI you entered in LI? Looking at the console logs it appears it is something like http://<destination>/. The URI needs to point to one of the supported endpoints. I suspect you want http://<destination>/endpoint/slack. If you navigate to http://<destination>/ in a web browser it should list the supported endpoints.

**Comment by KKelling** [comment]
In Log Insight the URI is "http://a.b.c.d:5001"   (where a.b.c.d. is the IP address of where the shim lives).

If I browse to that URI I see the list of supported endpoints 
![2](https://user-images.githubusercontent.com/31494687/36645170-d289f658-1a32-11e8-8a87-292d5906b68c.png)

**Comment by vmw-loginsight** [comment]
Awesome, so in LI you need to change the URL to: http://a.b.c.d:5001/endpoint/slack

**Comment by KKelling** [comment]
Do I need to append s/slack to the IP address?

**Comment by KKelling** [comment]
ok Thanks! )

**Comment by vmw-loginsight** [comment]
Assuming this is working now -- closing
