### ISSUE TITLE
opsgenie using Content type 'application/octet-stream' causing 415 

### ISSUE THREAD

**Issue by schen414** [vmw-loginsight/webhook-shims#67]
Content type is not set in opsgenie.py causing 415

**Comment by vmw-loginsight** [comment]
Hmm, thanks for reporting -- let me take a look

**Comment by vmw-loginsight** [comment]
Yup, definitely an issue -- pull request soon

**Comment by schen414** [comment]
Thanks

**Comment by flands** [comment]
Merged -- unrelated issue with bugzilla tests led to an unexpected delay.
