### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by johnddias** [vmw-loginsight/webhook-shims#76]
Please let me know if this repo is still maintained and if pull requests are still being accepted.

**Comment by ellieayla** [comment]
I've switched jobs. I'm not sure who the new owner of this repo is.

**Comment by ellieayla** [comment]
John, do you want to take ownership?

**Comment by ellieayla** [comment]
Or can you work with @haroyana ?

**Comment by johnddias** [comment]
Yes, I'd be happy to co-maintain with @haroyana - can we also add @prydin ?

**Comment by flands** [comment]
Done
